import typing


class SettingsManager:
    path: str
    settings: typing.Dict[str, typing.Any]
    def __init__(self, name: str, settings_directory: str | None = None) -> None: ...
    def read(self) -> None: ...
    def commit(self) -> None: ...
    def getSetting(self, key: str, defaults: typing.Any = None) -> typing.Any: ...
    def setSetting(self, key: str, value: typing.Any) -> None: ...
